package models

type VwSbhData struct {
	SbhStatus      int     `json:"sbh_status"`
	IDAri          int     `json:"id_ari"`
	ID             int     `json:"id"`
	NoSpat         string  `json:"no_spat"`
	KodeKatLahan   string  `json:"kode_kat_lahan"`
	KodePlant      string  `json:"kode_plant"`
	KodeAffd       string  `json:"kode_affd"`
	KodeBlok       string  `json:"kode_blok"`
	TglSpta        string  `json:"tgl_spta"`
	TebangPg       int     `json:"tebang_pg"`
	AngkutPg       int     `json:"angkut_pg"`
	JenisSpta      string  `json:"jenis_spta"`
	NoAngkutan     string  `json:"no_angkutan"`
	NamaPetani     string  `json:"nama_petani"`
	IDPetani       string  `json:"id_petani"`
	DeskripsiBlok  string  `json:"deskripsi_blok"`
	LuasHa         float64 `json:"luas_ha"`
	HaTertebang    float64 `json:"ha_tertebang"`
	TglTebang      string  `json:"tgl_tebang"`
	BrixSel        float64 `json:"brix_sel"`
	PhSel          float64 `json:"ph_sel"`
	DitolakSel     int     `json:"ditolak_sel"`
	DitolakAlasan  string  `json:"ditolak_alasan"`
	CetakSptaTgl   string  `json:"cetak_spta_tgl"`
	SelektorTgl    string  `json:"selektor_tgl"`
	TimbNettoTgl   string  `json:"timb_netto_tgl"`
	MejaTebuTgl    string  `json:"meja_tebu_tgl"`
	AriTgl         string  `json:"ari_tgl"`
	SbhTgl         string  `json:"sbh_tgl"`
	HariGiling     int     `json:"hari_giling"`
	TglGiling      string  `json:"tgl_giling"`
	Bruto          int     `json:"bruto"`
	Tara           int     `json:"tara"`
	NettoFinal     int     `json:"netto_final"`
	KondisiTebu    string  `json:"kondisi_tebu"`
	Daduk          int     `json:"daduk"`
	Sogolan        int     `json:"sogolan"`
	Pucuk          int     `json:"pucuk"`
	AkarTanah      int     `json:"akar_tanah"`
	NonTebu        int     `json:"non_tebu"`
	Terbakar       int     `json:"terbakar"`
	Cacahan        int     `json:"cacahan"`
	Brondolan      int     `json:"brondolan"`
	PersenBrixAri  float64 `json:"persen_brix_ari"`
	PersenPolAri   float64 `json:"persen_pol_ari"`
	PhAri          float64 `json:"ph_ari"`
	Hk             float64 `json:"hk"`
	NilaiNira      float64 `json:"nilai_nira"`
	FaktorRendemen float64 `json:"faktor_rendemen"`
	RendemenAri    float64 `json:"rendemen_ari"`
	AkuTgl         string  `json:"aku_tgl"`
	HablurAri      float64 `json:"hablur_ari"`
	GulaTotal      float64 `json:"gula_total"`
	TetesTotal     float64 `json:"tetes_total"`
	RendemenPtr    float64 `json:"rendemen_ptr"`
	GulaPtr        float64 `json:"gula_ptr"`
	TetesPtr       float64 `json:"tetes_ptr"`
	GulaPg         float64 `json:"gula_pg"`
	TetesPg        float64 `json:"tetes_pg"`
}
